# Generated by Django 6.1.2 on 2026-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
