# Generated by Django 6.1 on 2026-10-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferreteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
