# Generated by Django 6.1 on 2026-10-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferreteria', '0002_producto_archivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
